### ISSUE TITLE
logout not working

### ISSUE THREAD

**Issue by brettin** [brettin/oxcart#8]
The user logout does nothing, settings and profiles redirect to a stub. Suggest removing user profile and settings from the pull down list, and making logout work.

![screen shot 2015-01-15 at 10 10 37 am](https://cloud.githubusercontent.com/assets/991769/5761102/cd4cb0be-9c9e-11e4-867c-9f5362fd40df.png)

**Comment by nconrad** [comment]
Thanks!

**Comment by nconrad** [comment]
I guess I shouldn't close this until it is merged.
